global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    #auth
    #scheme: http
    #basic_auth:
      #username: username
      #assword: password
    static_configs:
      #- targets: ['localhost:9090']
      #- targets: ['host.docker.internal:8000']  # If Laravel runs on your host machine. Targets: should only contain the host and port, not the path.
      - targets: ['my_filament_laravel_12-laravel.test-1:80']  # dont foregt to create common network first before , see Readme
